language: python

# Travis doesn't support 3.7 by default, but if we run it on xenial it works
matrix:
  fast_finish: true
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
    sudo: required
    dist: xenial
  - python: pypy
  - python: pypy3

install:
  - pip install . coverage coveralls flake8 sphinx sphinx sphinx-argparse

script:
  - make flake
  - make coverage
  - cd docs; make doctest; make html

after_success:
  - coveralls

cache:
  pip: true
